/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* GreenLED */
#define GreenLED_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreenLED_0_INBUF_ENABLED 0u
#define GreenLED_0_INIT_DRIVESTATE 0u
#define GreenLED_0_INIT_MUXSEL 0u
#define GreenLED_0_INPUT_SYNC 2u
#define GreenLED_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreenLED_0_NUM 1u
#define GreenLED_0_PORT GPIO_PRT1
#define GreenLED_0_SLEWRATE CY_GPIO_SLEW_FAST
#define GreenLED_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define GreenLED_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreenLED_INBUF_ENABLED 0u
#define GreenLED_INIT_DRIVESTATE 0u
#define GreenLED_INIT_MUXSEL 0u
#define GreenLED_INPUT_SYNC 2u
#define GreenLED_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreenLED_NUM 1u
#define GreenLED_PORT GPIO_PRT1
#define GreenLED_SLEWRATE CY_GPIO_SLEW_FAST
#define GreenLED_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
